In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [2]:
url = "https://raw.githubusercontent.com/rolandmueller/titanic/main/titanic3.csv"
df = pd.read_csv(url)

df.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [3]:
df.isnull().sum()

pclass          0
survived        0
name            0
sex             0
age           263
sibsp           0
parch           0
ticket          0
fare            1
cabin        1014
embarked        2
boat          823
body         1188
home.dest     564
dtype: int64

In [4]:
df["age"] = df["age"].fillna(df["age"].median())
df["fare"] = df["fare"].fillna(df["fare"].median())
df["embarked"] = df["embarked"].fillna(df["embarked"].mode()[0])

df = df.drop(columns=["cabin"])

df.isnull().sum()

pclass          0
survived        0
name            0
sex             0
age             0
sibsp           0
parch           0
ticket          0
fare            0
embarked        0
boat          823
body         1188
home.dest     564
dtype: int64

In [5]:
df["title"] = df["name"].str.extract(r',\s*([^.]+)\.')

df["title"] = df["title"].replace(
    ["Capt","Col","Major","Dr","Rev","Don","Sir","Lady",
     "Jonkheer","Dona","Countess","Mme","Ms","Mlle"],
    "Rare"
)

In [6]:
df["familysize"] = df["sibsp"] + df["parch"] + 1

In [7]:
le = LabelEncoder()

df["sex"] = le.fit_transform(df["sex"])
df["title"] = le.fit_transform(df["title"])

In [8]:
df = pd.get_dummies(df, columns=["embarked", "pclass"])

In [9]:
scaler = StandardScaler()

df[["age", "fare", "sibsp", "parch", "familysize"]] = scaler.fit_transform(
    df[["age", "fare", "sibsp", "parch", "familysize"]]
)

In [10]:
df = df.drop(columns=["name", "ticket", "boat", "body", "home.dest"])

In [11]:
df.head()

,survived,sex,age,sibsp,parch,fare,title,familysize,embarked_C,embarked_Q,embarked_S,pclass_1,pclass_2,pclass_3
0,1,0,-0.039005,-0.479087,-0.445000,3.442584,1,-0.558346,False,False,True,True,False,False
1,1,1,-2.215952,0.481288,1.866526,2.286639,0,1.336749,False,False,True,True,False,False
2,0,0,-2.131977,0.481288,1.866526,2.286639,1,1.336749,False,False,True,True,False,False
3,0,1,0.038512,0.481288,1.866526,2.286639,2,1.336749,False,False,True,True,False,False
4,0,0,-0.349075,0.481288,1.866526,2.286639,3,1.336749,False,False,True,True,False,False